DROP SEQUENCE PRACOWNICY_SEQ;
DROP SEQUENCE PRZEWOZENIE_SEQ;
DROP SEQUENCE PAKOWANIE_SEQ;
DROP SEQUENCE ETAP_SEQ;
DROP SEQUENCE SAMOCHODY_SEQ;
DROP SEQUENCE SAMOCHOD_DOSTAWCY_SEQ;
DROP SEQUENCE KLIENCI_SEQ;
DROP SEQUENCE PACZKI_SEQ;
DROP SEQUENCE LISTY_SEQ;
DROP SEQUENCE FAKTURY_SEQ;
DROP SEQUENCE POZYCJA_FAKTURY_SEQ;

CREATE SEQUENCE PRACOWNICY_SEQ;
CREATE SEQUENCE PRZEWOZENIE_SEQ;
CREATE SEQUENCE PAKOWANIE_SEQ;
CREATE SEQUENCE ETAP_SEQ;
CREATE SEQUENCE SAMOCHODY_SEQ;
CREATE SEQUENCE SAMOCHOD_DOSTAWCY_SEQ;
CREATE SEQUENCE KLIENCI_SEQ;
CREATE SEQUENCE PACZKI_SEQ;
CREATE SEQUENCE LISTY_SEQ;
CREATE SEQUENCE FAKTURY_SEQ;
CREATE SEQUENCE POZYCJA_FAKTURY_SEQ;


--KLIENCI
INSERT INTO KLIENCI
VALUES(KLIENCI_SEQ.NEXTVAL,'Adam','Ząbek','Katowice','Polna',1,'36-200','885932159');
 
INSERT INTO KLIENCI
VALUES(KLIENCI_SEQ.NEXTVAL,'Piotr','Dziąsło','Koluszki','Dolna',11,'31-300','665720683');
 
INSERT INTO KLIENCI
VALUES(KLIENCI_SEQ.NEXTVAL,'Anna','Podkowa','Piasków','Rosoła',7,'96-100','413728260');
 
INSERT INTO KLIENCI
VALUES(KLIENCI_SEQ.NEXTVAL,'Grzegorz','Kowalski','Kraków','Górna',12,'52-400','602789567');
 
INSERT INTO KLIENCI
VALUES(KLIENCI_SEQ.NEXTVAL,'Beata','Wiśniewska','Warszawa','Maltańska',15,'34-800','749658432');
 
 
--PRACOWNICY
INSERT INTO PRACOWNICY
VALUES(PRACOWNICY_SEQ.NEXTVAL,'Lech','Muszyński','1956.01.02',10000,'Kielce','Długa',5,'735971052');
 
INSERT INTO PRACOWNICY
VALUES(PRACOWNICY_SEQ.NEXTVAL,'Daniel','Kiełbus','1995.05.03',1000,'Kielce','Krótka',12,'502381396');
 
INSERT INTO PRACOWNICY
VALUES(PRACOWNICY_SEQ.NEXTVAL,'Maria','Perepeczko','1985.10.13',2500,'Smyków','Wyjściowa',3,'602753157');
 
INSERT INTO PRACOWNICY
VALUES(PRACOWNICY_SEQ.NEXTVAL,'Leon','Kania','1994.02.12',3400,'Barcza','Dolna',4,'513485247');
 
INSERT INTO PRACOWNICY
VALUES(PRACOWNICY_SEQ.NEXTVAL,'Łukasz','Niebudek','1992.01.24',2800,'Zagnańsk','Turystyczna',11,'503781648');
 
 
 
 
--SAMOCHODY
INSERT INTO SAMOCHODY
VALUES(SAMOCHODY_SEQ.NEXTVAL,'Audi','Q7',2012,'TK 05937');
 
INSERT INTO SAMOCHODY
VALUES(SAMOCHODY_SEQ.NEXTVAL,'Volkswagen','Transporter',1999,'TK 12397');
 
INSERT INTO SAMOCHODY
VALUES(SAMOCHODY_SEQ.NEXTVAL,'Fiat','Dukato',2000,'TK 12AD9');
 
INSERT INTO SAMOCHODY
VALUES(SAMOCHODY_SEQ.NEXTVAL,'Ford','Transit',2005,'LU 13W45');
 
INSERT INTO SAMOCHODY
VALUES(SAMOCHODY_SEQ.NEXTVAL,'Iveco','Daily',2006,'WR 2A4B3');
 
INSERT INTO SAMOCHODY
VALUES(SAMOCHODY_SEQ.NEXTVAL,'Iveco','Daily',2001,'WW 3ER34'); 
 
 
--SAMOCHOD_DOSTAWCY
INSERT INTO SAMOCHOD_DOSTAWCY
VALUES(SAMOCHOD_DOSTAWCY_SEQ.NEXTVAL,2,1);
 
INSERT INTO SAMOCHOD_DOSTAWCY
VALUES(SAMOCHOD_DOSTAWCY_SEQ.NEXTVAL,3,2);
 
INSERT INTO SAMOCHOD_DOSTAWCY
VALUES(SAMOCHOD_DOSTAWCY_SEQ.NEXTVAL,5,3);
 
INSERT INTO SAMOCHOD_DOSTAWCY
VALUES(SAMOCHOD_DOSTAWCY_SEQ.NEXTVAL,4,4);

INSERT INTO SAMOCHOD_DOSTAWCY
VALUES(SAMOCHOD_DOSTAWCY_SEQ.NEXTVAL,6,5); 

 
 
 
 
--PAKOWANIE(TYLKO ID=3 PAKUJE)
INSERT INTO PAKOWANIE
VALUES (PAKOWANIE_SEQ.NEXTVAL,'Pudełko',3);
 
INSERT INTO PAKOWANIE
VALUES (PAKOWANIE_SEQ.NEXTVAL,'Zabezpieczone',3);
 
INSERT INTO PAKOWANIE
VALUES (PAKOWANIE_SEQ.NEXTVAL,'Koperta',3);
 
INSERT INTO PAKOWANIE
VALUES (PAKOWANIE_SEQ.NEXTVAL,'Koperta',3);
 
INSERT INTO PAKOWANIE
VALUES (PAKOWANIE_SEQ.NEXTVAL,'Zabezpieczone',3);
 
 
 
 
--PRZEWOZENIE
INSERT INTO PRZEWOZENIE
VALUES(PRZEWOZENIE_SEQ.NEXTVAL,'Katowice','Boska',1,1);
 
INSERT INTO PRZEWOZENIE
VALUES(PRZEWOZENIE_SEQ.NEXTVAL,'Kraków','Mała',7,1);
 
INSERT INTO PRZEWOZENIE
VALUES(PRZEWOZENIE_SEQ.NEXTVAL,'Rawa Mazowiecka','Krótka',5,3);
 
INSERT INTO PRZEWOZENIE
VALUES(PRZEWOZENIE_SEQ.NEXTVAL,'Kielce','Warszawska',12,2);
 
INSERT INTO PRZEWOZENIE
VALUES(PRZEWOZENIE_SEQ.NEXTVAL,'Rawa Mazowiecka','Krótka',33,4);
 
 
 
 
--ETAP
INSERT INTO ETAP
VALUES(ETAP_SEQ.NEXTVAL,2,'SPAKOWANA','NIE',1,1);
 
INSERT INTO ETAP
VALUES(ETAP_SEQ.NEXTVAL,1,'WYSŁANA','NIE',2,2);
 
INSERT INTO ETAP
VALUES(ETAP_SEQ.NEXTVAL,0,'DOSTARCZONA','TAK',3,3);
 
INSERT INTO ETAP
VALUES(ETAP_SEQ.NEXTVAL,1,'WYSŁANA','NIE',4,4);
 
INSERT INTO ETAP
VALUES(ETAP_SEQ.NEXTVAL,2,'SPAKOWANA','NIE',5,5);
 
 
 
 
--PACZKI
INSERT INTO PACZKI
VALUES(PACZKI_SEQ.NEXTVAL,'DO KILOGRAMA',NULL,1,20,10,10,1,4);
 
INSERT INTO PACZKI
VALUES(PACZKI_SEQ.NEXTVAL,'2-5 KILOGRAMA',NULL,2,40,30,20,2,1);
 
INSERT INTO PACZKI
VALUES(PACZKI_SEQ.NEXTVAL,'LIST',NULL,0,0,0,0,3,2);
 
INSERT INTO PACZKI
VALUES(PACZKI_SEQ.NEXTVAL,'LIST',NULL,0,0,0,0,4,3);
 
INSERT INTO PACZKI
VALUES(PACZKI_SEQ.NEXTVAL,'5-10 KILOGRAMÓW',NULL,5,40,35,10,5,1);

/*INSERT INTO PACZKI
VALUES(PACZKI_SEQ.NEXTVAL,'5-10 KILOGRAMÓW',NULL,7,50,40,20,5,3);*/
 
--LIST PRZEWOZOWY

INSERT INTO LISTY_PRZEWOZOWE
VALUES(LISTY_SEQ.NEXTVAL,'Warszawa','Luźna',15,'Płock','Czarma',3,1); 

INSERT INTO LISTY_PRZEWOZOWE
VALUES(LISTY_SEQ.NEXTVAL,'Warszawa','Domaszewskiego',5,'Katowice','Świętej Anny',7,2);

INSERT INTO LISTY_PRZEWOZOWE
VALUES(LISTY_SEQ.NEXTVAL,'Kielce','Wiosenna',13,'Gdańsk','Pokątna',41,3);

INSERT INTO LISTY_PRZEWOZOWE
VALUES(LISTY_SEQ.NEXTVAL,'Warszawa','Domaszewskiego',5,'Radzyń','Piłsudskiego',10,4);

INSERT INTO LISTY_PRZEWOZOWE
VALUES(LISTY_SEQ.NEXTVAL,'Warszawa','Luźna',15,'Bydgoszcz','Krótka',77,5);
 
--FAKTURY
INSERT INTO FAKTURY
VALUES(FAKTURY_SEQ.NEXTVAL,'2018.10.09',3,1);
 
INSERT INTO FAKTURY
VALUES(FAKTURY_SEQ.NEXTVAL,'2018.10.09',3,2);
 
INSERT INTO FAKTURY
VALUES(FAKTURY_SEQ.NEXTVAL,'2018.10.10',3,3);
 
INSERT INTO FAKTURY
VALUES(FAKTURY_SEQ.NEXTVAL,'2018.10.10',3,3);
 
INSERT INTO FAKTURY
VALUES(FAKTURY_SEQ.NEXTVAL,'2018.11.11',3,4);
 
 
 
 
--POZYCJA_FAKTURY
INSERT INTO POZYCJA_FAKTURY
VALUES(POZYCJA_FAKTURY_SEQ.NEXTVAL,1,1);
 
INSERT INTO POZYCJA_FAKTURY
VALUES(POZYCJA_FAKTURY_SEQ.NEXTVAL,2,2);
 
INSERT INTO POZYCJA_FAKTURY
VALUES(POZYCJA_FAKTURY_SEQ.NEXTVAL,3,3);
 
INSERT INTO POZYCJA_FAKTURY
VALUES(POZYCJA_FAKTURY_SEQ.NEXTVAL,4,4);
 
INSERT INTO POZYCJA_FAKTURY
VALUES(POZYCJA_FAKTURY_SEQ.NEXTVAL,5,5);
