--1. Wyświetl zestawienie dostawców, ile dostarczyli paczek, imię i nazwisko
 
select p.imie,p.nazwisko,count(*) ile_dostaw from pracownicy p
join przewozenie prz on p.id_pracownika=prz.id_pracownika
group by p.imie,p.nazwisko;
 
--2. Wyświetl jakim samochodem dowozi paczki pracownik o id 2 (imię, nazwisko i samochód).
 
select p.imie,p.nazwisko,s.marka,s.model_samochodu from pracownicy p
join samochod_dostawcy sd on p.id_pracownika=sd.id_pracownika
inner join samochody s on sd.id_samochodu=s.id_samochodu
where p.id_pracownika=2;

 
--3. Wyświetl informacje o kliencie, który nadal najwięcej paczek.
 
SELECT k.imie,k.nazwisko,COUNT(p.id_klienta) LICZBA_PACZEK FROM KLIENCI K
INNER JOIN PACZKI P 
ON P.ID_klienta=k.Id_klienta
GROUP BY k.imie,k.nazwisko
HAVING COUNT(P.ID_KLIENTA)=(SELECT MAX(COUNT(P.ID_KLIENTA)) FROM PACZKI P GROUP BY P.ID_KLIENTA);
 
 
--4. Wyświetl informacje o kliencie, który wydal najwięcej.
 
SELECT K.IMIE,K.NAZWISKO,SUM(P.CENA) WYDANA_KWOTA FROM PACZKI P
INNER JOIN KLIENCI K
ON P.ID_KLIENTA=K.ID_KLIENTA
GROUP BY K.ID_KLIENTA,K.IMIE,K.NAZWISKO
HAVING SUM(P.CENA)=(SELECT MAX(SUM(CENA)) FROM PACZKI GROUP BY ID_KLIENTA);
 
 
--5. Wyświetl paczki, które były dostarczane najstarszym samochodem.
 
SELECT P.ID_PACZKI,S.ROK_PRODUKCJI FROM PACZKI P
JOIN ETAP E ON e.id_etapu=p.id_etapu
INNER JOIN PRZEWOZENIE PRZ ON PRZ.ID_PRZEWOZU=E.ID_PRZEWOZU
JOIN PRACOWNICY PR ON pRZ.id_pracownika=pr.id_pracownika
INNER JOIN SAMOCHOD_DOSTAWCY SD ON SD.ID_PRACOWNIKA=PR.ID_PRACOWNIKA
INNER JOIN SAMOCHODY S ON S.ID_SAMOCHODU=SD.ID_SAMOCHODU
INNER JOIN (SELECT MIN(ROK_PRODUKCJI) MRP FROM SAMOCHODY)
ON MRP=S.ROK_PRODUKCJI;
 
 
--6. Wyświetl wszystkie paczki, które nie zostały dostarczone (od najnowszych do najstarszych).
 
SELECT P.ID_PACZKI, F.DATA_WYSTAWIENIA FROM PACZKI P
JOIN POZYCJA_FAKTURY PF ON pf.id_paczki=p.id_paczki
INNER JOIN ETAP E ON E.ID_ETAPU=P.ID_ETAPU
INNER JOIN FAKTURY F ON F.ID_FAKTURY=PF.ID_FAKTURY
WHERE e.czy_dostarczona='NIE'
ORDER BY f.data_wystawienia DESC;
 
 
--7.Zsumuj ile firma zarobi na przesyłkach w poszczególnych miesiącach.
 
SELECT EXTRACT(MONTH FROM F.DATA_WYSTAWIENIA) MIESIAC,SUM(P.CENA) PRZYCHÓD
FROM PACZKI P
JOIN POZYCJA_FAKTURY PF
ON PF.ID_PACZKI=P.ID_PACZKI
INNER JOIN FAKTURY F
ON F.ID_FAKTURY=PF.ID_FAKTURY
GROUP BY EXTRACT(MONTH FROM F.DATA_WYSTAWIENIA);
 
 
--8. Wyświetl dane o pracowniku i ilość paczek, które zostały zapakowane w kopertę
 
SELECT PR.IMIE,PR.NAZWISKO,COUNT(*) LICZBA_KOPERT
FROM PRACOWNICY PR
JOIN PAKOWANIE PA ON PA.ID_PRACOWNIKA=PR.ID_PRACOWNIKA
INNER JOIN ETAP E
ON E.ID_PAKOWANIA=PA.ID_PAKOWANIA
INNER JOIN PACZKI P
ON P.ID_ETAPU=E.ID_ETAPU
WHERE PA.RODZAJ_OPAKOWANIA='Koperta'
GROUP BY PR.IMIE,PR.NAZWISKO;
 
  
--9. Stworz widok, w którym będzie imię, nazwisko i numer telefonu klientów, którzy nie otrzymali jeszcze przesyłki
 
CREATE OR REPLACE VIEW NIE_DOSTARCZONE AS
SELECT K.IMIE,K.NAZWISKO,K.NUMER_TELEFONU FROM KLIENCI K
JOIN PACZKI P
ON P.ID_KLIENTA=K.ID_KLIENTA
JOIN ETAP E
ON E.ID_ETAPU=P.ID_ETAPU
WHERE E.CZY_DOSTARCZONA='NIE'
GROUP BY K.IMIE,K.NAZWISKO,K.NUMER_TELEFONU;
 
SELECT * FROM NIE_DOSTARCZONE;
DROP VIEW NIE_DOSTARCZONE CASCADE CONSTRAINTS; 

--10. Wyświetl pracowników, którzy są w wieku mniejszym niż średnia wieku pracowników.
SELECT P.IMIE,P.NAZWISKO,(EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM P.DATA_URODZENIA)) WIEK 
FROM PRACOWNICY P
WHERE (SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-EXTRACT(YEAR FROM P.DATA_URODZENIA) < (SELECT AVG((SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL)-EXTRACT(YEAR FROM P.DATA_URODZENIA)) FROM PRACOWNICY P);

--11.STWORZ WIDOK W KTORYM BEDA ID_PACZKI ORAZ INFORMACJE O KLIENTOW KTORYCH PACZKA MA NAJDLUZY CZAS OCZEKIWANIA
CREATE OR REPLACE VIEW NAJDLUZSZY_CZAS AS
SELECT P.ID_PACZKI,K.IMIE,K.NAZWISKO,K.NUMER_TELEFONU FROM KLIENCI K
JOIN PACZKI P ON P.ID_KLIENTA=K.ID_KLIENTA
INNER JOIN ETAP E ON E.ID_ETAPU=P.ID_ETAPU
INNER JOIN (SELECT MAX(DLUGOSC_OCZEKIWANIA) MDO FROM ETAP) 
ON MDO=E.DLUGOSC_OCZEKIWANIA;

SELECT * FROM NAJDLUZSZY_CZAS;
DROP VIEW NAJDLUZSZY_CZAS CASCADE CONSTRAINTS;


--12.WYSWIETL SAMOCHODY KTORE NIE SA UZYWANE PRZY DOSTARCZANIU PACZEK
SELECT * FROM SAMOCHODY S
WHERE NOT EXISTS(SELECT * FROM SAMOCHOD_DOSTAWCY SD 
WHERE SD.ID_SAMOCHODU=S.ID_SAMOCHODU);
